import type { Metadata } from "next";
import { Provider as QueryClientProvider } from "~/utils/react-query";
import Container from "~/views/wrappers/container";

import "~/styles/globals.css";

export const metadata: Metadata = {
  title: "Academic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <QueryClientProvider>
          <Container>{children}</Container>
        </QueryClientProvider>
      </body>
    </html>
  );
}
